// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4adjEsy35GIvL2eLyyCykUnFMYgth00',
    appId: '1:571062070316:web:5bf24584867c0caaf73589',
    messagingSenderId: '571062070316',
    projectId: 'gramaurja-31706',
    authDomain: 'gramaurja-31706.firebaseapp.com',
    storageBucket: 'gramaurja-31706.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3JEW9wkywqDTZGQ-LoyeFQ4Jyl7DNKT8',
    appId: '1:571062070316:android:8c23f063b0dd7385f73589',
    messagingSenderId: '571062070316',
    projectId: 'gramaurja-31706',
    storageBucket: 'gramaurja-31706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3Aq7EXDOUUUnS_bcvv9N1TJRyqbQnTM',
    appId: '1:571062070316:ios:6059dde92c5b865df73589',
    messagingSenderId: '571062070316',
    projectId: 'gramaurja-31706',
    storageBucket: 'gramaurja-31706.firebasestorage.app',
    iosBundleId: 'com.example.gramaUrja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3Aq7EXDOUUUnS_bcvv9N1TJRyqbQnTM',
    appId: '1:571062070316:ios:6059dde92c5b865df73589',
    messagingSenderId: '571062070316',
    projectId: 'gramaurja-31706',
    storageBucket: 'gramaurja-31706.firebasestorage.app',
    iosBundleId: 'com.example.gramaUrja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg4adjEsy35GIvL2eLyyCykUnFMYgth00',
    appId: '1:571062070316:web:c19495eddfbc7326f73589',
    messagingSenderId: '571062070316',
    projectId: 'gramaurja-31706',
    authDomain: 'gramaurja-31706.firebaseapp.com',
    storageBucket: 'gramaurja-31706.firebasestorage.app',
  );
}
